### ISSUE TITLE
GC cannot destroy an object of type 'map' as it can't see all references.

### ISSUE THREAD

**Issue by glcolor** [Sami-Vuorela/aatc#1] opened 2015-09-19 02:57 UTC
Code:
void main() 
{  
    map<int,int>@   m_Map=map<int,int>();
}

When script engine releases,it reports:
Warning : There is an external reference to an object in module '', preventing it from being deleted
Info    : The builtin type in previous message is named 'map'
Error   : Object {0}. GC cannot destroy an object of type 'map' as it can't see all references. Current ref count is -1.

**Comment by Sami-Vuorela** [comment] 2015-09-24 16:57
That code doesn't even compile (template parameters missing and all that), you're gonna have to give me a more reproductible error case than that if you want support.

This code doesn't seem to have problems with the GC:

```
void scriptmain(){
  map<string,int>@ forgottenmap_s_i = map<string,int>();
  map<int,string>@ forgottenmap_i_s = map<int,string>();
  map<int,int>@ forgottenmap_i_i = map<int,int>();
  map<string,string>@ forgottenmap_s_s = map<string,string>();
}
```

**Comment by glcolor** [comment] 2015-10-01 13:25
Sorry for the unclear description before.
AS ver:SVN 2236
aatc ver:latest commit
code (modified from as_test project in as sdk):

``` cpp
 engine = asCreateScriptEngine(ANGELSCRIPT_VERSION);
    engine->SetMessageCallback(asMETHOD(COutStream,Callback), &out, asCALL_THISCALL);
    RegisterStdString(engine);
    RegisterScriptArray(engine, false);
    aatc_RegisterAllContainers(engine);

    asIScriptModule *mod = engine->GetModule(0, asGM_ALWAYS_CREATE);
    mod->AddScriptSection("test",
            "void main() { \n"
            "  map<int,string>@ m_Map=map<int,string>();"
            "} \n");
    r = mod->Build();

   asIScriptContext *ctx = engine->CreateContext();
    r = ExecuteString(engine, "main()", mod, ctx);
    ctx->Release();

    engine->Release();
```

console output:

```
AngelScript version: 2.31.0 WIP DEBUG
AngelScript options:  AS_DEBUG AS_WIN AS_X86
 (0, 0) : Warning : There is an external reference to an object in module '', preventing it from being deleted
 (0, 0) : Info    : The builtin type in previous message is named 'map'
 (0, 0) : Error   : Object {0}. GC cannot destroy an object of type 'map' as it can't see all references. Current ref count is -1.
```

**Comment by Sami-Vuorela** [comment] 2015-10-03 14:40
Looks like I've never actually been destroying the script contexts in my tests and this is a real nasty memory leak indeed.

I have committed a fix to the garbage collection problems in a new branch "2015-sep-gc-fix"

You can grab the new version here
https://github.com/Sami-Vuorela/aatc/archive/2015-sep-gc-fix.zip

It seems to work properly in all my tests and in my game project. Simple containers like your example are actually getting destructed and so are circular-dependency monstrosity maps referencing lists referencing vectors containing maps.
Comment here if it works properly for you and I will close the issue and throw the fix at the master branch.

**Comment by glcolor** [comment] 2015-10-06 05:01
I tested the branch,it's ok now,thanks a lot.

**Closed as completed** 2015-10-06 09:56 UTC
